// src/utils/seedData.js
// Initial demo data loaded on first visit

import { generateId } from './storage';

export const seedCategories = [
  { id: 'cat1', name: 'Popüler', slug: 'populer', isActive: true, imageUrl: 'https://picsum.photos/seed/cat1/400/300' },
  { id: 'cat2', name: 'Yeni', slug: 'yeni', isActive: true, imageUrl: 'https://picsum.photos/seed/cat2/400/300' },
  { id: 'cat3', name: 'Özel', slug: 'ozel', isActive: true, imageUrl: 'https://picsum.photos/seed/cat3/400/300' },
  { id: 'cat4', name: 'Premium', slug: 'premium', isActive: true, imageUrl: 'https://picsum.photos/seed/cat4/400/300' },
  { id: 'cat5', name: 'HD', slug: 'hd', isActive: true, imageUrl: 'https://picsum.photos/seed/cat5/400/300' },
];

export const seedModels = [
  { id: 'mod1', name: 'Sophia Rose', bio: 'Profesyonel içerik üreticisi', isActive: true, imageUrl: 'https://picsum.photos/seed/mod1/300/300' },
  { id: 'mod2', name: 'Emma Night', bio: 'Özel içerik modeli', isActive: true, imageUrl: 'https://picsum.photos/seed/mod2/300/300' },
  { id: 'mod3', name: 'Aria Star', bio: 'Premium içerik üreticisi', isActive: true, imageUrl: 'https://picsum.photos/seed/mod3/300/300' },
  { id: 'mod4', name: 'Luna Vega', bio: 'VIP içerik modeli', isActive: false, imageUrl: 'https://picsum.photos/seed/mod4/300/300' },
];

export const seedVideos = [
  {
    id: 'vid1',
    title: 'Yaz Günü Özel',
    description: 'Güneşli bir yaz gününde özel çekim.',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://picsum.photos/seed/vid1/480/270',
    categoryId: 'cat1',
    modelId: 'mod1',
    isVIP: false,
    isActive: true,
    viewCount: 1240,
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'vid2',
    title: 'Gece Şovları',
    description: 'Gece boyunca özel performans.',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://picsum.photos/seed/vid2/480/270',
    categoryId: 'cat2',
    modelId: 'mod2',
    isVIP: false,
    isActive: true,
    viewCount: 890,
    createdAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'vid3',
    title: 'Özel VIP Seansı',
    description: 'Sadece VIP üyelere özel içerik.',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://picsum.photos/seed/vid3/480/270',
    categoryId: 'cat4',
    modelId: 'mod1',
    isVIP: true,
    isActive: true,
    viewCount: 3200,
    createdAt: new Date('2024-03-01').toISOString(),
  },
  {
    id: 'vid4',
    title: 'Sahil Macerası',
    description: 'Deniz kenarında romantik çekim.',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://picsum.photos/seed/vid4/480/270',
    categoryId: 'cat1',
    modelId: 'mod3',
    isVIP: false,
    isActive: true,
    viewCount: 560,
    createdAt: new Date('2024-03-05').toISOString(),
  },
  {
    id: 'vid5',
    title: 'VIP Gece Özel',
    description: 'Gecenin karanlığında özel performans.',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://picsum.photos/seed/vid5/480/270',
    categoryId: 'cat3',
    modelId: 'mod2',
    isVIP: true,
    isActive: true,
    viewCount: 4500,
    createdAt: new Date('2024-03-10').toISOString(),
  },
  {
    id: 'vid6',
    title: 'Tatil Anıları',
    description: 'Unutulmaz tatil klibi.',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://picsum.photos/seed/vid6/480/270',
    categoryId: 'cat5',
    modelId: null,
    isVIP: false,
    isActive: true,
    viewCount: 210,
    createdAt: new Date('2024-03-15').toISOString(),
  },
  {
    id: 'vid7',
    title: 'VIP Koleksiyon',
    description: 'En özel anlar bir arada.',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://picsum.photos/seed/vid7/480/270',
    categoryId: 'cat4',
    modelId: 'mod3',
    isVIP: true,
    isActive: true,
    viewCount: 2800,
    createdAt: new Date('2024-03-20').toISOString(),
  },
  {
    id: 'vid8',
    title: 'Sabah Çekimi',
    description: 'Sabahın erken saatlerinde özel klip.',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://picsum.photos/seed/vid8/480/270',
    categoryId: 'cat2',
    modelId: 'mod1',
    isVIP: false,
    isActive: true,
    viewCount: 340,
    createdAt: new Date('2024-03-25').toISOString(),
  },
];

export const ADMIN_USER = {
  id: 'admin-001',
  username: 'admin',
  password: 'admin123',
  role: 'admin',
  isVIP: true,
  createdAt: new Date().toISOString(),
};
